
version: 1.0.{build}-{branch}

image: Ubuntu

environment:
  matrix:
    - JDK_VERSION: 1.7
    
# install:
#   - apt install default-jdk
  
before_test:
  - java --version

platform: Any CPU

configuration: Release

hosts:
  queue-server: 127.0.0.1
  
on_success:
  - cmd: echo "Successfully build"
  - cmd: cd code && java main.java

on_failure:
  - cmd: echo "Build Failed"


environment:
    matrix:
        - NAME: Visual Studio Code
